# Generated by Django 2.2.4 on 2019-08-07 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'In Stock'), (1, 'Out of Stock')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('color_code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('availability_status', models.IntegerField(choices=[(0, 'In Stock'), (1, 'Out of Stock')], default=0)),
                ('photo', models.ImageField(upload_to='')),
                ('description', models.URLField(max_length=128, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expense', models.DecimalField(decimal_places=2, max_digits=5)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actual_discount', models.IntegerField()),
                ('spent_time', models.DecimalField(decimal_places=1, max_digits=3)),
                ('colors', models.ManyToManyField(related_name='hats', through='assortment.Availability', to='assortment.Color')),
                ('consumables', models.ManyToManyField(related_name='hats', to='accounting.Consumable')),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_options', to='assortment.Color'),
        ),
        migrations.AddField(
            model_name='availability',
            name='hat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assortment.Hat'),
        ),
    ]
